global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: python-app
    metrics_path: /
    static_configs:
      - targets:
          - 'dummy-service-0:8000'
          - 'dummy-service-1:8000'
          - 'dummy-service-2:8000'
