{
 "title": "HomeWork dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (quantile) (\r\n  request_latency_ms{quantile=~\"0.5|0.75|0.9|0.95|0.99\", instance=~\"$Instance\"}\r\n)\r\n",
     "legendFormat": "{{quantile}} procentile"
    }
   ]
  },
  {
   "title": "RPS by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (\r\n  increase(\r\n    responses_total{instance=~\"$Instance\", code=~\"2xx|3xx|4xx|5xx\"}[1m]\r\n  )\r\n)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 * sum (\r\n  increase(\r\n    responses_total{instance=~\"$Instance\", code=~\"4xx|5xx\"}[1m]\r\n  )\r\n) / sum (\r\n  increase(\r\n    responses_total{instance=~\"$Instance\", code=~\"2xx|3xx|4xx|5xx\"}[1m]\r\n  )\r\n)",
     "legendFormat": "Error"
    },
    {
     "expr": "100 * sum (\r\n  increase(\r\n    responses_total{instance=~\"$Instance\", code=~\"2xx|3xx\"}[1m]\r\n  )\r\n) / sum (\r\n  increase(\r\n    responses_total{instance=~\"$Instance\", code=~\"2xx|3xx|4xx|5xx\"}[1m]\r\n  )\r\n)",
     "legendFormat": "Success"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mem_total_mb{instance=~\"$Instance\"})",
     "legendFormat": "total_mb"
    },
    {
     "expr": "sum(mem_used_mb{instance=~\"$Instance\"})",
     "legendFormat": "used_mb"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cpu_work_time_ms{instance=~\"$Instance\"})",
     "legendFormat": "work_time"
    },
    {
     "expr": "sum(cpu_idle_time_ms{instance=~\"$Instance\"})",
     "legendFormat": "idle_time"
    }
   ]
  }
 ]
}