version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=code_architecture_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    code_architecture-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          - POSTGRES_DB=code_architecture_db_1
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/code_architecture/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/code_architecture:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /code_architecture
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
